/// Folds the roster into "what does the world look like right now".
///
/// A port of `bridge/lib/presence.js`. There is one question worth asking about
/// the people in a space: **is anybody following me**. It is read from
/// `followTargetId` on their own `SpaceUser` row, so it is *observed* rather than
/// guessed, and it means what it says — somebody deliberately attached themselves
/// to you and is walking over to talk.
///
/// What used to be here, and why it is not missed:
///
///  - Proximity. Standing near someone's avatar says nothing about intent: people
///    park at desks, walk past on the way somewhere else, and loiter at the
///    threshold. It generated by far the most events and the least meaning.
///  - The movement-based follow detector. It existed because the desktop log had no
///    `followTargetId` to read. With the real field always present, guessing from
///    convergence is strictly worse.
///  - Per-player mic/camera/screenshare. Those came from the client's log and are
///    in no Gather model at all. `speaking` — live voice activity — is in the game
///    state and is the better signal: it says who is *talking*.
library;

import 'package:gather_events/gather_events.dart';

import 'game_protocol.dart';

/// Ignore a repeat wave from the same person inside this window.
///
/// A wave is a deliberate act, which is why nothing else here is rate limited. The
/// wave *button* is not: one person produced 41 `WaveEvent`s in eight seconds while
/// this was being measured. One wave per person per window is a record of
/// something; 41 identical rows is not.
const waveCooldown = Duration(seconds: 30);

/// What the fold produced: events worth showing a human, and whether the snapshot
/// needs republishing.
class FoldResult {
  const FoldResult({this.emit = const [], this.stateChanged = false});

  final List<GatherEvent> emit;
  final bool stateChanged;
}

/// Mutable accumulator for one other person.
class _Player {
  _Player(this.id);

  final String id;
  String? name;
  bool inSpace = true;
  bool isFollowingMe = false;
  bool speaking = false;
  DateTime? followingMeSince;

  PlayerRef toRef() => PlayerRef(
        id: id,
        name: name,
        inSpace: inSpace,
        isFollowingMe: isFollowingMe,
        speaking: speaking,
        followingMeSince: followingMeSince,
      );
}

class PresenceTracker {
  final Map<String, _Player> _players = {};

  SelfState _self = const SelfState();
  CollectorHealth _health = const CollectorHealth();
  PartyState _party = const PartyState();

  /// My own SpaceUser id, learned from the roster. Follow is judged against it.
  String? _selfId;

  /// senderId -> when we last reported a wave from them. See [waveCooldown].
  final Map<String, DateTime> _wavedAt = {};

  SelfState get self => _self;
  CollectorHealth get health => _health;
  PartyState get party => _party;
  String? get selfId => _selfId;
  List<PlayerRef> get players =>
      _players.values.map((p) => p.toRef()).toList(growable: false);

  PresenceSnapshot snapshot() => PresenceSnapshot(
        at: DateTime.now(),
        self: _self,
        players: players,
        health: _health,
        party: _party,
      );

  void setHealth(CollectorHealth health) => _health = health;
  void setParty(PartyState party) => _party = party;

  /// Forget everyone. Called when the space changes, since a roster from one space
  /// says nothing about another.
  void clearRoom() => _players.clear();

  _Player _player(String id) => _players.putIfAbsent(id, () => _Player(id));

  /// Best available name for a player id, for wording a notification.
  String nameFor(String? id) {
    if (id == null) return 'Someone';
    final name = _players[id]?.name;
    if (name != null && name.isNotEmpty) return name;
    return 'Someone';
  }

  /// The space we are watching, and what it is called.
  FoldResult applySpace({String? spaceId, String? spaceName}) {
    final changed = spaceId != null && spaceId != _self.spaceId;
    _self = _self.copyWith(spaceId: spaceId, spaceName: spaceName);
    if (changed) clearRoom();
    return FoldResult(
      emit: [
        SpaceChangedEvent(
          at: DateTime.now(),
          source: EventSource.gather,
          spaceId: _self.spaceId,
          spaceName: _self.spaceName,
        ),
      ],
      stateChanged: true,
    );
  }

  /// One interaction: a bus event, or a meeting row the reader judged to be news.
  ///
  /// Everything here is something a *person* did, aimed at *you*. An unrecognised
  /// `eventName` is dropped rather than guessed at — it has no wording, and
  /// inventing one for a lock screen is worse than silence.
  FoldResult applyInteraction(BusEvent event) {
    // Without knowing which SpaceUser is ours, "aimed at me" is unanswerable — the
    // same stance this class takes on being followed. Reporting every wave in the
    // space would be worse than reporting none.
    if (event.name != 'ChatBroadcastNewMessage' && !event.isFor(_selfId)) {
      return const FoldResult();
    }

    final now = DateTime.now();
    // The sender's own clock beats ours when it is offered.
    final at = DateTime.tryParse(event.sentTime ?? '') ?? now;
    final who = nameFor(event.senderId);

    switch (event.name) {
      case 'WaveEvent':
        // The wave *button* is not a decision the way a wave is: one person produced
        // 41 in eight seconds. One per person per window is a record of something.
        final key = event.senderId ?? 'unknown';
        final last = _wavedAt[key];
        if (last != null && now.difference(last) < waveCooldown) {
          return const FoldResult();
        }
        _wavedAt[key] = now;
        return FoldResult(emit: [
          NotificationShownEvent(
            at: at,
            source: EventSource.gather,
            notificationType: 'wave',
            body: '$who waved at you',
            senderId: event.senderId,
          ),
        ]);

      case 'MeetingInvite':
        // `MeetingParticipant` with our id and somebody else's `inviterId`. Read from
        // state rather than scraped from the desktop client's log, which is where
        // this used to come from — so it arrives without that client running, and it
        // knows who invited us.
        return FoldResult(emit: [
          NotificationShownEvent(
            at: at,
            source: EventSource.gather,
            notificationType: 'meeting invite',
            title: 'Meeting invite',
            body: '$who invited you to a meeting',
            senderId: event.senderId,
          ),
        ]);

      case 'MeetingJoinRequest':
        // Somebody knocking on a meeting we are in, before anyone has answered. The
        // one signal here with a deadline attached: on the observed sample the gap
        // between the request and the answer was two seconds, so it is worthless
        // late.
        return FoldResult(emit: [
          NotificationShownEvent(
            at: at,
            source: EventSource.gather,
            notificationType: 'meeting join request',
            title: 'Someone wants to join',
            body: '$who is asking to join your meeting',
            senderId: event.senderId,
          ),
        ]);

      case 'ChatBroadcastNewMessage':
        final message = event.payload['message'];
        if (message is! Map<String, Object?>) return const FoldResult();
        final text = message['message'];
        // Gather emits empty system rows on the same channel as real messages —
        // every meeting join writes one. They are not chat.
        if (text is! String || text.isEmpty) return const FoldResult();
        final sender = message['spaceUserId'];
        if (sender is String && sender == _selfId) return const FoldResult();
        return FoldResult(emit: [
          ChatMessageEvent(
            at: at,
            source: EventSource.gather,
            playerId: sender is String ? sender : (event.senderId ?? 'unknown'),
            text: text,
            channel: message['chatChannelId'] as String?,
          ),
        ]);

      default:
        return const FoldResult();
    }
  }

  /// Replace what we know from Gather's own `SpaceUser` records.
  FoldResult applyRoster(Roster roster) {
    final emit = <GatherEvent>[];
    var stateChanged = false;
    final at = DateTime.now();

    final spaceName = roster.spaceName;
    if (spaceName != null && spaceName != _self.spaceName) {
      _self = _self.copyWith(spaceName: spaceName);
      stateChanged = true;
    }

    if (roster.selfId != null) _selfId = roster.selfId;
    RosterRow? me;
    for (final row in roster.rows) {
      if (row.id == _selfId) {
        me = row;
        break;
      }
    }

    // Whether *you* are in the space at all. Our own connection is an observer — it
    // never calls `enterSpace` — so this reflects your real clients, not us. Your
    // avatar does not disappear when you close Gather; it stays parked wherever you
    // left it, so `connected` is the only honest answer.
    if (me != null) {
      final selfOnline = me.connected != false;
      if (_self.inOffice != selfOnline) {
        _self = _self.copyWith(inOffice: selfOnline);
        stateChanged = true;
      }
      if (me.followTargetKnown && me.followTargetId != _self.followingPlayerId) {
        _self = me.followTargetId == null
            ? _self.copyWith(clearFollowing: true)
            : _self.copyWith(followingPlayerId: me.followTargetId);
        stateChanged = true;
      }
    }

    // Without knowing which row is *me*, "following me" is undefined — there is
    // nothing for `followTargetId` to point at. Merge the names the roster does give
    // us and judge nothing.
    final knowSelf = _selfId != null;
    final seen = <String>{};

    for (final row in roster.rows) {
      if (row.id.isEmpty || row.id == _selfId) continue;
      seen.add(row.id);
      final p = _player(row.id);

      final name = row.name;
      if (name != null && name != p.name) {
        p.name = name;
        stateChanged = true;
      }

      if (row.speaking != null && row.speaking != p.speaking) {
        // State only, never an event: voice activity toggles every few seconds while
        // someone talks, and a feed of that is unreadable.
        //
        // It is also only a *state change* for somebody the screen draws — which is
        // exactly the people following you. A measured space held 79 rows, so
        // counting every one made a stranger three rooms away clearing their throat
        // rebuild the whole widget tree. Whoever is invisible keeps the new value, so
        // it is already correct if they *do* start following you.
        final visible = p.isFollowingMe;
        p.speaking = row.speaking!;
        if (visible) stateChanged = true;
      }

      // Following: their followTargetId pointing at me is the real thing, no
      // heuristics needed.
      if (knowSelf && row.followTargetKnown) {
        final followsMe = row.followTargetId == _selfId;
        if (followsMe != p.isFollowingMe) {
          p.isFollowingMe = followsMe;
          p.followingMeSince = followsMe ? at : null;
          stateChanged = true;
          emit.add(FollowEvent(
            at: at,
            source: EventSource.gather,
            followerId: row.id,
            targetId: _selfId ?? 'self',
            started: followsMe,
            targetIsSelf: true,
          ));
        }
      }

      if (row.connected != null && p.inSpace != row.connected) {
        p.inSpace = row.connected!;
        stateChanged = true;
      }
    }

    // Anyone previously in the roster but absent now has left.
    if (knowSelf && roster.rows.isNotEmpty) {
      for (final entry in _players.entries) {
        final p = entry.value;
        if (seen.contains(entry.key) || !p.inSpace) continue;
        p.inSpace = false;
        if (p.isFollowingMe) {
          p.isFollowingMe = false;
          p.followingMeSince = null;
          emit.add(FollowEvent(
            at: at,
            source: EventSource.gather,
            followerId: entry.key,
            targetId: _selfId ?? 'self',
            started: false,
            targetIsSelf: true,
          ));
        }
        stateChanged = true;
      }
    }

    return FoldResult(emit: emit, stateChanged: stateChanged);
  }
}
