/**
 * Folds the roster into "what does the world look like right now".
 *
 * There is one question worth asking about the people in a space: **is anybody
 * following me**. It is read from `followTargetId` on their own `SpaceUser` row,
 * so it is *observed* rather than guessed, and it means what it says — somebody
 * deliberately attached themselves to you and is walking over to talk.
 *
 * What used to be here, and why it is not missed:
 *
 *  - Proximity. Standing near someone's avatar says nothing about intent: people
 *    park at desks, walk past on the way somewhere else, and loiter at the
 *    threshold. It generated by far the most events and the least meaning, and
 *    the thresholds and hysteresis it needed existed only to make that noise
 *    tolerable rather than useful.
 *  - The movement-based follow detector. It existed because the log had no
 *    `followTargetId` to read. With the real field always present, guessing from
 *    convergence is strictly worse — and it had already stopped being reachable.
 *  - Per-player mic/camera/screenshare. Those came from the client's log and are
 *    in no Gather model at all. `speaking` — live voice activity — is in the game
 *    state and is the better signal anyway: it says who is *talking*, not who
 *    happens to have a mic enabled.
 *
 * One log-derived event still passes through `apply`: `notification.shown`, for
 * the waves and meeting invites Gather's own client raises. It needs no folding —
 * it is news, not state — so it falls through to the default branch.
 */

import { bridgeStatus, emptySelf, follow, newPlayer } from './events.js';

export class PresenceTracker {
  constructor() {
    /** @type {Map<string, object>} */
    this._players = new Map();
    this._self = emptySelf();
    this._health = { gather: false, cdp: false, logTail: false, detail: null };
    /** My own SpaceUser id, learned from the roster. Follow is judged against it. */
    this._selfId = null;
  }

  get self() {
    return this._self;
  }

  get health() {
    return this._health;
  }

  get players() {
    return [...this._players.values()];
  }

  snapshot() {
    return {
      type: 'presence.snapshot',
      at: new Date().toISOString(),
      self: this._self,
      players: this.players,
      health: this._health,
    };
  }

  setHealth(patch) {
    this._health = { ...this._health, ...patch };
  }

  _player(id) {
    let p = this._players.get(id);
    if (!p) {
      p = newPlayer(id);
      this._players.set(id, p);
    }
    return p;
  }

  /**
   * Apply one event the collector produced directly, rather than via the roster.
   *
   * That is now a short list — status and the space the bridge was told to watch.
   * Everything about *people* comes through `applyRoster`.
   *
   * Returns `{ emit, stateChanged }` where `emit` holds only the events worth
   * showing a human.
   */
  apply(event) {
    switch (event.type) {
      case 'self.changed': {
        const before = { ...this._self };
        if (event.userId != null) this._self.userId = event.userId;
        if (event.inOffice != null) this._self.inOffice = event.inOffice;
        const changed =
          before.userId !== this._self.userId || before.inOffice !== this._self.inOffice;
        if (!changed) return { emit: [], stateChanged: false };
        return { emit: [event], stateChanged: true };
      }

      case 'space.changed': {
        const changed = event.spaceId != null && event.spaceId !== this._self.spaceId;
        if (event.spaceId != null) this._self.spaceId = event.spaceId;
        if (event.spaceName != null) this._self.spaceName = event.spaceName;
        if (changed) this._clearRoom();
        return { emit: [event], stateChanged: true };
      }

      case 'bridge.status': {
        const patch = {
          [event.collector]: event.healthy,
          detail: event.detail ?? this._health.detail,
        };
        // `cdp` is a compatibility alias, not a second collector. App builds
        // already on people's phones compute `hasRichData` from
        // `CollectorHealth.cdp`, so publishing only the honest name would make
        // them show the "log-only mode: no names" banner while we hold the full
        // roster. Newer builds read `gather` and ignore this.
        if (event.collector === 'gather') patch.cdp = event.healthy;
        this.setHealth(patch);
        return { emit: [event], stateChanged: true };
      }

      default:
        return { emit: [event], stateChanged: false };
    }
  }

  _clearRoom() {
    this._players.clear();
  }

  /**
   * Replace what we know from Gather's own `SpaceUser` records.
   *
   * @param {{ selfId: string|null, rows: Array<object>, spaceName?: string|null }} roster
   * @returns {{ emit: object[], stateChanged: boolean }}
   */
  applyRoster({ selfId, rows, spaceName = null }) {
    const emit = [];
    let stateChanged = false;
    const at = new Date();

    if (spaceName && spaceName !== this._self.spaceName) {
      this._self.spaceName = spaceName;
      stateChanged = true;
    }

    if (selfId) this._selfId = selfId;
    const me = rows.find((r) => r.id === this._selfId) ?? null;

    // Whether *you* are in the space at all. Our own connection is an observer —
    // it never calls `enterSpace` — so this reflects your real clients, not us.
    // Your avatar does not disappear when you close Gather; it stays parked
    // wherever you left it, so `connected` is the only honest answer.
    const selfOnline = me?.connected !== false;
    if (me && this._self.inOffice !== selfOnline) {
      this._self.inOffice = selfOnline;
      stateChanged = true;
    }

    if (me && me.followTargetId !== undefined) {
      const wanted = me.followTargetId ?? null;
      if (wanted !== this._self.followingPlayerId) {
        this._self.followingPlayerId = wanted;
        stateChanged = true;
      }
    }

    // Without knowing which row is *me*, "following me" is undefined — there is
    // nothing for `followTargetId` to point at. Merge the names the roster does
    // give us and judge nothing.
    const knowSelf = this._selfId != null;

    const seen = new Set();

    for (const row of rows) {
      if (!row?.id || row.id === this._selfId) continue;
      seen.add(row.id);
      const p = this._player(row.id);

      if (row.name && row.name !== p.name) {
        p.name = row.name;
        stateChanged = true;
      }
      if (row.speaking != null && row.speaking !== p.speaking) {
        // State only, never an event: voice activity toggles every few seconds
        // while someone talks, and a feed of that is unreadable.
        //
        // It is also only a *state change* for somebody the app draws — which is
        // now exactly the people following you. The measured space holds 79 rows,
        // so counting every one of them made a stranger three rooms away clearing
        // their throat publish a 23 KiB roster to every phone. That was the bulk
        // of an observed 0.86 snapshots/second, ~1.1 MB/minute, which is what made
        // the link feel fragile: the phone spent its time decoding rosters and
        // rebuilding its whole widget tree. Whoever is invisible keeps the new
        // value on the player record, so it is already correct in the snapshot
        // that goes out if they *do* start following you.
        const visible = p.isFollowingMe;
        p.speaking = row.speaking;
        if (visible) stateChanged = true;
      }

      // Following: their followTargetId pointing at me is the real thing, no
      // heuristics needed.
      if (knowSelf && row.followTargetId !== undefined) {
        const followsMe = row.followTargetId === this._selfId;
        if (followsMe !== p.isFollowingMe) {
          p.isFollowingMe = followsMe;
          p.followingMeSince = followsMe ? at.toISOString() : null;
          stateChanged = true;
          emit.push(
            follow({
              at,
              followerId: row.id,
              targetId: this._selfId ?? 'self',
              started: followsMe,
              targetIsSelf: true,
            }),
          );
        }
      }

      if (row.connected != null && p.inSpace !== row.connected) {
        p.inSpace = row.connected;
        stateChanged = true;
      }
    }

    // Anyone previously in the roster but absent now has left.
    for (const [id, p] of this._players) {
      if (!knowSelf) break;
      if (seen.has(id) || !p.inSpace) continue;
      if (rows.length === 0) break; // an empty roster means "unknown", not "empty"
      p.inSpace = false;
      if (p.isFollowingMe) {
        p.isFollowingMe = false;
        p.followingMeSince = null;
        emit.push(
          follow({
            at,
            followerId: id,
            targetId: this._selfId ?? 'self',
            started: false,
            targetIsSelf: true,
          }),
        );
      }
      stateChanged = true;
    }

    return { emit, stateChanged };
  }

  statusEvent(collector, healthy, detail) {
    this.setHealth({ [collector]: healthy, detail: detail ?? null });
    return bridgeStatus({ at: new Date(), collector, healthy, detail });
  }
}
